ALTER TABLE users
ADD COLUMN share_phones TINYINT(1) DEFAULT 1,
ADD COLUMN share_emails TINYINT(1) DEFAULT 1,
ADD COLUMN share_addresses TINYINT(1) DEFAULT 1,
ADD COLUMN ignore_unknown TINYINT(1) DEFAULT 0;

ALTER TABLE contacts
ADD COLUMN share_phones TINYINT(1) DEFAULT 0,
ADD COLUMN share_emails TINYINT(1) DEFAULT 0,
ADD COLUMN share_addresses TINYINT(1) DEFAULT 0;
